services:
  web:
    build: .
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-True}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-127.0.0.1,localhost}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-17896}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE:-require}
    ports:
      - "8000:8000"
    command: >
      sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
